import type { DebriefData, PerChunkRow } from './index';

export interface PrCommentDraft {
	markdown: string;
	warnings: string[];
}

export function buildPrCommentDraft(debrief: DebriefData, findings?: Array<{ category: string; severityHint?: string | null; file: string; line: number; message: string; suggestion?: string }>): PrCommentDraft {
	const warnings: string[] = [];
	const lines: string[] = [];

	lines.push('## Lectern Review Summary');
	lines.push('');
	lines.push(`**Confidence:** ${debrief.confidenceScore}% — ${bandEmoji(debrief.band)} ${debrief.band.charAt(0).toUpperCase() + debrief.band.slice(1)}`);
	lines.push(`**Recommendation:** ${debrief.recommendation}`);
	lines.push('');

	const totalAnswered = debrief.perChunk.reduce((s, c) => s + c.answered, 0);
	const totalQuestions = debrief.perChunk.reduce((s, c) => s + c.total, 0);
	const approxPassed = debrief.perChunk.reduce((s, c) => s + Math.round(c.score * c.answered), 0);
	lines.push(`**Score:** ${approxPassed}/${totalAnswered} questions correct across ${debrief.perChunk.length} chunks`);
	lines.push('');

	if (findings && findings.length > 0) {
		lines.push('### Key Findings');
		lines.push('');
		for (const f of findings.slice(0, 10)) {
			const loc = `\`${f.file}:${f.line}\``;
			lines.push(`- **${f.category}** ${loc}: ${f.message}`);
			if (f.suggestion) {
				lines.push(`  > ${f.suggestion}`);
			}
		}
		if (findings.length > 10) {
			lines.push(`- …and ${findings.length - 10} more`);
		}
		lines.push('');
	}

	const weakChunks = debrief.perChunk.filter((c) => c.score < 0.5);
	if (weakChunks.length > 0) {
		lines.push('### Weak Spots');
		lines.push('');
		for (const c of weakChunks) {
			lines.push(`- **${c.title}** — ${Math.round(c.score * 100)}% (${c.note})`);
		}
		lines.push('');
	}

	if (debrief.missedByTag.length > 0) {
		lines.push('### Topics to Review');
		lines.push('');
		for (const m of debrief.missedByTag.slice(0, 5)) {
			lines.push(`- \`${m.tag}\` — ${m.missCount} miss${m.missCount === 1 ? '' : 'es'}`);
		}
		lines.push('');
	}

	if (debrief.followUps.length > 0) {
		lines.push('### Follow-ups');
		lines.push('');
		for (const f of debrief.followUps) {
			lines.push(`- ${f}`);
		}
		lines.push('');
	}

	lines.push('---');
	lines.push('*Generated by [Lectern](https://github.com/user/lectern) — guided PR review.*');

	if (totalAnswered === 0) {
		warnings.push('No questions were answered — the comment may not reflect actual review depth.');
	}

	return { markdown: lines.join('\n'), warnings };
}

function bandEmoji(band: DebriefData['band']): string {
	return band === 'high' ? '🟢' : band === 'medium' ? '🟡' : '🔴';
}
